version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - npm install
      - npm run build
      - aws s3 sync $CODEBUILD_SRC_DIR/build s3://$BUCKET_NAME/ --delete --only-show-errors