version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - yarn install
      - npx ng build
  post_build:
    commands:
      - zip -r -q build.zip dist/
artifacts:
  files:
    - build.zip