version: 0.2
phases:
  install:
    commands:
      - n 19.1.0
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - zip -r -q build.zip dist/
artifacts:
  files:
    - build.zip