version: 0.2
phases:
  install:
    commands:
      - n 16.14.1
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - zip -r -q build.zip build/
artifacts:
  files:
    - build.zip