version: 0.2
phases:
  install:
    commands:
      - n 16.0.0
  build:
    commands:
      - npm install
      - npm run build
      - ls -ali src
      - ls
      - pwd
      - echo $BUCKET_NAME
      - ls -ali build
  post_build:
    commands:
      - zip -r -q build.zip build/
      - echo $CLOUDFRONT_ID
      - aws s3 sync build/ s3://$BUCKET_NAME/ --delete --only-show-errors
artifacts:
  files:
    - build.zip

