version: 0.2
phases:
  build:
    commands:
      - unzip -q $CODEBUILD_SRC_DIR/build.zip
      - ls -la $CODEBUILD_SRC_DIR
      - ls -la $CODEBUILD_SRC_DIR/build
      - aws s3 sync $CODEBUILD_SRC_DIR/build s3://$BUCKET_NAME/ --delete --only-show-errors
