version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - yarn install
      - npx ng build
      - aws s3 sync $CODEBUILD_SRC_DIR/dist/apps/private s3://$BUCKET_NAME/ --delete --only-show-errors
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
