version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - yarn install
      - npx ng build
      - echo "<html><h1>Hi index here</h1></html>" >> index.html
  post_build:
    commands:
      - zip build.zip index.html
artifacts:
  files:
    - build.zip
