version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - yarn install
      - npx ng build
      - ls
      - pwd
      - echo $BUCKET_NAME
      - aws s3 sync dist/apps/private s3://"${BUCKET_NAME}"/ --delete --only-show-errors
      - BUCKET_NAME=cloudfront-content-sharing-bucket
      - aws s3 sync dist/apps/private s3://"${BUCKET_NAME}"/ --delete --only-show-errors
      - echo $CLOUDFRONT_ID
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_ID}" --paths "/*"

