version: 0.2
phases:
  install:
    commands:
      - n 14.18.2
  build:
    commands:
      - yarn install
      - npx ng build
      - ls -ali src
      - ls
      - pwd
      - echo $BUCKET_NAME
      - ls -ali dist
      - echo $CLOUDFRONT_ID
      - aws s3 sync dist/ s3://$BUCKET_NAME/ --delete --only-show-errors
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

